# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "APIKit" = "sha256-mGHze7KIKWQA/o/sPVYoc/Qw1NWJ2aG7jAUxoNCTE3o=";
    "Flatten" = "sha256-Zt9XJl+A/2GEKMRByYQv3ass9iA5+ky5xEbpHScBw8g=";
    "HeliumLogger" = "sha256-OZ4XDjsalOYGedmpM/b87kuoO2wietfncLbDIjgbABQ=";
    "LoggerAPI" = "sha256-hPdLYtM4YSm9s3YHNFjWaYoPlv2dBApKcr4qi8K7srs=";
    "SHList" = "sha256-5G9EdIkaxMHosRR+wCMSxNo3IPZv8SvCyQlTT0iz6XE=";
    "swift-argument-parser" = "sha256-ibNKHxIHJWpafIggyDSChvI15+YnLwsej8B10tm8ZKU=";
    "swift-html-entities" = "sha256-NqUsHznGJFYsqIITaKxQcqVXtP9L7YeJ+LhdBtod8cQ=";
    "swift-log" = "sha256-yqYg7Yq12qWnBp858cMPsOFgPaho53+tU5J2vCKgKrs=";
    "SwiftParamTest" = "sha256-8BOKiT6QMP6zbiJYuBoxK+KJGBmg93FPOBhCor9MNIk=";
    "XcodeEdit" = "sha256-5mlxIX8EOdOAhp96jN9pY94zndCiMDX0qpS+Apx5278=";
    "Yams" = "sha256-dDvt+LWwwWgcge5kSa+oXdfXK0njWtkAxt44Qnu+lCw=";
  };
}
