#!/usr/bin/env bash
set -euo pipefail

# This script cannot be triggered from `nix build`: Nix builds are read-only
# (cannot update nix/default.nix) and sandboxed with no network access
# (cannot compute dependency hashes).

if ! command -v jq >/dev/null || ! command -v nurl >/dev/null; then
  exec nix shell nixpkgs#jq nixpkgs#nurl --command "$0" "$@"
fi

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
spm_workspace_state="$root/.build/workspace-state.json"
out_dir="$root/nix"
default_nix="$out_dir/default.nix"

if [[ ! -f "$spm_workspace_state" ]]; then
  echo "SwiftPM workspace state not found at $spm_workspace_state" >&2
  echo "Run 'swift package resolve' to generate it." >&2
  exit 1
fi

mkdir -p "$out_dir"

hashes=""
while IFS=$'\t' read -r identity url rev; do
  echo "-- Fetching $identity" >&2
  hash="$(nurl "$url" "$rev" --json --submodules=true --fetcher=fetchgit | jq -r .args.hash)"
  hashes+="
    \"${identity}\" = \"${hash}\";"
done < <(jq -r '.object.dependencies[] | [.packageRef.identity, .packageRef.location, .state.checkoutState.revision] | @tsv' "$spm_workspace_state")

cat > "$default_nix" <<EOF
# This file was generated by Tools/nix/update-swiftpm2nix.sh.
{
  workspaceStateFile = ../.build/workspace-state.json;
  hashes = {$hashes
  };
}
EOF

echo "Wrote $default_nix" >&2
