#!/usr/bin/env bash
set -euo pipefail

# This script cannot be triggered from `nix build`: Nix builds are read-only
# (cannot update nix/default.nix) and sandboxed with no network access
# (cannot compute dependency hashes).

if ! command -v jq >/dev/null || ! command -v nurl >/dev/null; then
  exec nix shell nixpkgs#jq nixpkgs#nurl --command "$0" "$@"
fi

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
pkg_resolved="$root/Package.resolved"
out_dir="$root/nix"
workspace_state="$out_dir/workspace-state.json"
default_nix="$out_dir/default.nix"

if [[ ! -f "$pkg_resolved" ]]; then
  echo "Package.resolved not found at $pkg_resolved" >&2
  exit 1
fi

mkdir -p "$out_dir"

jq -n --slurpfile resolved "$pkg_resolved" '
  {
    object: {
      artifacts: [],
      dependencies: ($resolved[0].pins | map({
        basedOn: null,
        packageRef: {
          identity: .identity,
          kind: "remoteSourceControl",
          location: .location,
          name: .identity
        },
        state: {
          checkoutState: .state,
          name: "sourceControlCheckout"
        },
        subpath: .identity
      }))
    },
    version: 6
  }
' > "$workspace_state"

hashes=""
while IFS=$'\t' read -r identity url rev; do
  echo "-- Fetching $identity" >&2
  hash="$(nurl "$url" "$rev" --json --submodules=true --fetcher=fetchgit | jq -r .args.hash)"
  hashes+="
    \"${identity}\" = \"${hash}\";"
done < <(jq -r '.pins[] | [.identity, .location, .state.revision] | @tsv' "$pkg_resolved")

cat > "$default_nix" <<EOF
# This file was generated by Tools/nix/update-swiftpm2nix.sh.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {$hashes
  };
}
EOF

echo "Wrote $workspace_state and $default_nix" >&2
